server:
  http:
    port: 8080
    addr: 0.0.0.0
    cors:
      enabled: false
      origins:
        - "*"
  kcp:
    addr: 0.0.0.0
    port: 8081
    # 使用 "fast" 模式以获得最佳性能
    mode: "fast"
    # 不使用任何加密
    crypt: "none"
    # 发送窗口大小，设为 128
    sndwnd: 128
    # 接收窗口大小，设为 128
    rcvwnd: 128
    # 最大传输单元，设为 1400 字节
    mtu: 1400
    # 设置为 1 以启用快速模式
    noDelay: 1
    # 设置为 20 毫秒以减少延迟
    interval: 20
    # 设置为 2 以减少重传次数
    resend: 2
    # 设置为 1 以关闭拥塞控制
    nc: 1
log:
  # 这里有几个输出方案
  # stdout
  # stderr
  # <path>
  output:
    - "stdout"
    - "/var/log/waveform/latest.log"
  errOutput:
    - "stderr"
    - "/var/log/waveform/error.log"
  # e.g. json console console_with_color
  format: json
  # 规范需要符合 zap 日志库的 zapcore.ParseLevel 的规范
  level: info

db:
  driver: sqlite
  dbName: waveform

